Add executeActionsEmail
fschmtt/keycloak-rest-api-client-php pull request #72
Opened 2023-09-28 15:19 UTC by JPRW10

2023-10-02 09:57 UTC, fschmtt commented
Hi, thanks for your contribution 🥳 

Do you mind adding some unit and integration test for this new endpoint?

There are a lot of examples already - let me know if I can assist you 😄

2023-10-02 14:14 UTC, JPRW10 commented
Hello!

I didn't add any unit or integration test because the endpoint is only sending a mail to specified user, basically there's nothing to test

Do you want me to add tests anyway?

2023-10-02 16:06 UTC, fschmtt commented
Yeah would be nice if you could add them:
* The unit test makes sure there's no unwanted & undetected change.
* The integration tests are run against all Keycloak versions since 13.0.0 and ensure that they work with all of them.

Thank you 😄

2023-10-03 11:04 UTC, fschmtt requested changes

2023-10-03 11:04 UTC, fschmtt commented on tests/Integration/Resource/UsersTest.php
> +    public function testExecuteActionsEmail(): void
I just tested it out locally - calling this endpoint actually requires a few setup steps (setting a user email address, setting up SMTP).

You can leave out the integration test IMO, thanks for your attempt, though 😄

2023-10-03 11:04 UTC, fschmtt commented on tests/Unit/Resource/UsersTest.php
> +    public function testExecuteActionsEmail(): void
```suggestion
public function testExecuteActionsEmail(): void
    {
        $command = new Command(
            '/admin/realms/{realm}/users/{userId}/execute-actions-email',
            Method::PUT,
            [
                'realm' => 'test-realm',
                'userId' => 'test-user-id',
            ],
        );

        $commandExecutor = $this->createMock(CommandExecutor::class);
        $commandExecutor->expects(static::once())
            ->method('executeCommand')
            ->with($command);

        $users = new Users(
            $commandExecutor,
            $this->createMock(QueryExecutor::class),
        );

        $users->executeActionsEmail('test-realm', 'test-user-id');
    }
```

2023-10-03 11:40 UTC, fschmtt approved these changes

2023-10-03 11:40 UTC, merged

2023-10-03 11:42 UTC, fschmtt commented
Thanks again, use 0.15.0 to use your changes 🥳