adjustments regarding the new subgroup behavior since keycloak 23.0.0
fschmtt/keycloak-rest-api-client-php pull request #81
Opened 2024-01-05 11:42 UTC by leon-manq

Hi,
frist of all nice libaray. Thank you for all the great work.
Since Keycloak 23.0.0 there is a new endpoint which is used to provide the subgroups of a group. 
GET /admin/realms/{realm}/groups/{id}/children
Retrieving information from the subgroup property is no longer possible. The array is empty.

2024-01-07 09:10 UTC, fschmtt commented on src/Representation/Group.php
> +        protected ?string $parentId = null,
Please add a getter and setter to the class's annotation (adhere to the order: getters first, setters second, alphabetical order).

2024-01-08 18:49 UTC, leon-manq commented
Thanks for the review. I have implemented the points you mentioned. PHP is not my primary language. It took a moment to understand the implementation of the getters and setters with reflection.

2024-01-12 08:44 UTC, fschmtt requested changes

2024-01-12 08:44 UTC, fschmtt commented on src/Resource/Groups.php
> +    public function create(string $realm, Group $group, ?string $parentGroupId = null): void
You forgot to remove the `$parentGroupId` parameter 🙂

2024-01-12 10:47 UTC, fschmtt commented
The current (integration) testing setup runs **all** tests against each Keycloak version.

Since the child group endpoints exist only in >= 23.0.0 we need to skip those tests when the version tested against is lower.

In #83 I added the possibility to skip tests depending on the Keycloak version.

In your case the test could look like this:
```php
public function testCreateChildGroup(): void
{
    $this->skipIfKeycloakVersionIsLessThan('23.0.0');

    $importedGroupName = Uuid::uuid4()->toString();
    $childGroupName = Uuid::uuid4()->toString();

    $groups = $this->getKeycloak()->groups();

    // Create group
    $groups->create('master', new Group(name: $importedGroupName),);
    $group = $groups->all('master')->first();
    static::assertInstanceOf(Group::class, $group);

    // Create child group
    $groups->createChild('master', new Group(name: $childGroupName), $group->getId());
    $childGroups = $groups->children('master', $group->getId());
    static::assertCount(1, $childGroups);

    $childGroup = $childGroups->first();
    static::assertInstanceOf(Group::class, $childGroup);
    static::assertSame($childGroupName, $childGroup->getName());
}
```

So, what you need to do:
* Rebase your branch to `main` 
* Adjust the `Groups` test (see suggestion above)

2024-01-12 22:51 UTC, fschmtt approved these changes

2024-01-12 22:51 UTC, merged

2024-01-12 22:53 UTC, fschmtt commented
Thanks for your contribution, I appreciate it! 🥳

The changes are included in the v0.17.0 release.